### ISSUE TITLE
Android devices logout of Google Account after using MoblieClient

### ISSUE THREAD

**Issue by JVMed** [simon-weber/gmusicapi#424]
I've got a script that is runs fine everyday (only using the MoblieClient interface APIs) and ~50% of the time after a few hours of the script ending, I get a persistant "Account Action Required" notification on each of my Android devices. I then need to tap on the notification to log into my account to get all my Google stuff syncing again. I do not get logged out on any desktop Chrome logins. The script is also not affected and always works. 

I have 2 step verification enabled on my Google account and the script uses an app password.   I've tried using different MAC addresses with the Mobileclient login and currently using the same MAC as my phone but my Android devices still get logged out. Anyone had this issue before? 

![persistant "Account Action Required" notification](http://i.stack.imgur.com/GAQlx.jpg)

**Comment by simon-weber** [comment]
I've never seen this, but I feel like someone has reported it here in the past. I can't find an issue for it though.

**Comment by dvirtz** [comment]
I'm having it too.

**Comment by simon-weber** [comment]
This would probably be fixed by https://github.com/simon-weber/gmusicapi/issues/426 if it pans out.

**Comment by Tadly** [comment]
I think this might be the same problem I had some time ago.
Are you sending a lot of request per second?

Check issue #367 and the workaround mentioned ;)

**Comment by JVMed** [comment]
@Tadly Your problem sounds like mine. Your authtoken [workaround](https://github.com/diraimondo/gmusicproxy/issues/34#issuecomment-147359198) looks like a solution (haven't tested it yet). How long does the authtoken login work? Does it expire after some time or uses?

Is this the issue you were thinking of @simon-weber ?

**Comment by Tadly** [comment]
@JVMed honestly I don't know and I never tested it.
I am however sending a test-request.

Basically I overloaded the login method in my own class which implements the workaround **and** sends a test-request `get_registered_devices()` within a `try: ... except: ...` block.
On failure, I do a *proper* login and preserve the new authtoken.

It's not very nice but works for now :)
This is a snippet from my add-on.
`_addon.getSetting` and `_addon.setSetting` should be self-explanatory
```python
class GMusic(Mobileclient):
    def login(self):
        username  = _addon.getSetting('username')
        password  = _addon.getSetting('password')
        device_id = _addon.getSetting('device_id')
        authtoken = _addon.getSetting('authtoken')

        if authtoken:
            self.android_id               = device_id
            self.session._authtoken       = authtoken
            self.session.is_authenticated = True

            try:
                # Send a test request to ensure our authtoken is still valide and working
                self.get_registered_devices()
                return True
            except:
                # Faild with the test-request so we set "is_authenticated=False"
                # and go through the login-process again to get a new "authtoken"
                self.session.is_authenticated = False

        if device_id:
            if super(GMusic, self).login(username, password, device_id):
                _addon.setSetting('authtoken', self.session._authtoken)
                return True

        # Prevent further execution in case we failed with the login-process
        raise SystemExit
```

**Comment by JVMed** [comment]
@Tadly Cool, I'll definitely test it out when I get a chance :+1:

**Comment by JVMed** [comment]
I am now using your login code @Tadly and will see over the next week or so if I get logged out of my Android devices. I haven't had an authtoken login failure yet unless I force one. 

So using this login technique, from Google's point of view, does it look like the same session/login because we are using the same authtoken instead of getting a new one on each login?

**Comment by Tadly** [comment]
> So using this login technique, from Google's point of view, does it look like the same session/login because we are using the same authtoken instead of getting a new one on each login?

I'm pretty sure on that one. Though, I don't quite know the source for the current login process.
Usually with OAuth you'd get the session-toke **and** both a *expires-at* and *refresh-token*.
The latter two are to (you might have guessed already) refresh a session without the users need to do anything.

Because gmusic isn't a public api (with proper documentation and such) the current login-process is a bit.. wonky and doesn't follow traditional processes (@simon-weber please correct me if I'm wrong).

But, as simon already mentioned, #426 would fix/improve quite a lot if it works out :)

**Comment by JVMed** [comment]
My problem is fixed. After using this authtoken method for a week, I have not yet been forcibly logged out of my google account on any Android devices which is great.

**Comment by thebigmunch** [comment]
> My problem is fixed. After using this authtoken method for a week, I have not yet been forcibly logged out of my google account on any Android devices which is great.

Correction, you have worked around the problem. The problem still exists, you've just made it so you don't encounter it.

**Comment by exp0nge** [comment]
@Tadly that code snippet that you provided generates `traceback.extract_stack()` errors (trying to find an instance of the client). Are you still using this package?

**Comment by tarcus69** [comment]
Was this issue ever resolved in the main library? I run a script once a day and regularly find all my android devices being logged out.

**Comment by simon-weber** [comment]
I'd forgotten about it, to be honest. The oauth/mobileclient stuff didn't work out, so we'd probably need https://github.com/simon-weber/gmusicapi/issues/367.

**Comment by soncaokim** [comment]
I confirm that the workaround proprosed here works.

**Comment by tarcus69** [comment]
I've implemented it too and have been running my script once an hour for about half a day, no logouts so far, normally I'd get logged out on my android devices about once a month when running my original script once a day so I'd estimate it would take about 30 authentications before my androids get logged out so if it survives for a few days being run once an hour without problems then it's looking good.

**Comment by simon-weber** [comment]
https://github.com/simon-weber/gmusicapi/issues/620#issuecomment-439731287 will fix this.

**Comment by simon-weber** [comment]
Ok, that's out in 11.1.0, so I'm going to close this. Clients will have to update to the [new OAuth interface](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.perform_oauth) to apply the fix.
